import React from 'react'
export const metadata = {
  title: 'Next App API Docs',
  description: 'Generated by Swagger',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
